name: 'gabrielbb/xvfb-action'
description: 'Run your headless tests with XVFB'
branding:
  icon: airplay
  color: white
inputs:
  run:
    description: 'Command to execute using xvfb'
    required: true
  skip-sudo:
    description: "Add this option with any value, if you want to run commands without sudo"
  working-directory:
    description: 'Directory to execute command on, defaults to ./'
    required: false
  options:
    description: 'XServer options'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
