name: 'smithki/xvfb-action'
description: 'Run your headless integration tests with XVFB and Node v16.x'
branding:
  icon: aperture
  color: yellow
inputs:
  run:
    description: 'Command to execute using xvfb'
    required: true
  working-directory:
    description: 'Directory to execute command on, defaults to ./'
    required: false
  options:
    description: 'XServer options'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
